version: '3.8'
services:
  db:
    image: 'postgres:15-alpine'
    container_name: db_postgres
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: booking_db
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    ports:
        - '1313:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  app:
    build: ./
    container_name: booking-book-api
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    restart: unless-stopped